name = "HypergeoMat"
uuid = "45a664f0-7593-4733-b76c-60f36ef4c15f"
authors = ["Stéphane Laurent <laurent_step@outlook.fr>"]
version = "0.1.0"

[deps]
GSL = "92c85e6c-cbff-5e0c-80f7-495c94daaecd"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
